import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function generatePDF(results, profile) {
  try {
    // Create a temporary div with the report content
    const reportDiv = document.createElement('div');
    reportDiv.style.position = 'absolute';
    reportDiv.style.left = '-9999px';
    reportDiv.style.width = '800px';
    reportDiv.style.padding = '40px';
    reportDiv.style.backgroundColor = 'white';
    reportDiv.style.fontFamily = 'Arial, sans-serif';
    
    reportDiv.innerHTML = `
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #4F46E5; font-size: 28px; margin-bottom: 10px;">NumenCoach</h1>
        <h2 style="color: #666; font-size: 18px;">Numerology Report</h2>
        <p style="color: #888; font-size: 14px;">Generated on ${new Date().toLocaleDateString('en-IN')}</p>
      </div>
      
      <div style="margin-bottom: 30px; padding: 20px; background: #f8f9fa; border-radius: 10px;">
        <h3 style="color: #333; margin-bottom: 15px;">Profile Information</h3>
        <p><strong>Name:</strong> ${profile.fullName}</p>
        ${profile.preferredName ? `<p><strong>Preferred Name:</strong> ${profile.preferredName}</p>` : ''}
        <p><strong>Date of Birth:</strong> ${profile.dob}</p>
        <p><strong>System:</strong> ${profile.system.charAt(0).toUpperCase() + profile.system.slice(1)}</p>
      </div>
      
      <div style="margin-bottom: 30px;">
        <h3 style="color: #333; margin-bottom: 15px;">Core Numbers</h3>
        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px;">
          <div style="text-align: center; padding: 15px; background: #f0f4ff; border-radius: 8px;">
            <div style="font-size: 24px; font-weight: bold; color: #4F46E5;">${results.lifePath.value}</div>
            <div style="font-size: 12px; color: #666;">Life Path</div>
          </div>
          <div style="text-align: center; padding: 15px; background: #f0f4ff; border-radius: 8px;">
            <div style="font-size: 24px; font-weight: bold; color: #4F46E5;">${results.expression.value}</div>
            <div style="font-size: 12px; color: #666;">Expression</div>
          </div>
          <div style="text-align: center; padding: 15px; background: #f0f4ff; border-radius: 8px;">
            <div style="font-size: 24px; font-weight: bold; color: #4F46E5;">${results.soulUrge.value}</div>
            <div style="font-size: 12px; color: #666;">Soul Urge</div>
          </div>
          <div style="text-align: center; padding: 15px; background: #f0f4ff; border-radius: 8px;">
            <div style="font-size: 24px; font-weight: bold; color: #4F46E5;">${results.personality.value}</div>
            <div style="font-size: 12px; color: #666;">Personality</div>
          </div>
          <div style="text-align: center; padding: 15px; background: #f0f4ff; border-radius: 8px;">
            <div style="font-size: 24px; font-weight: bold; color: #4F46E5;">${results.birthday}</div>
            <div style="font-size: 12px; color: #666;">Birthday</div>
          </div>
          <div style="text-align: center; padding: 15px; background: #f0f4ff; border-radius: 8px;">
            <div style="font-size: 24px; font-weight: bold; color: #4F46E5;">${results.maturity}</div>
            <div style="font-size: 12px; color: #666;">Maturity</div>
          </div>
        </div>
      </div>
      
      <div style="margin-bottom: 20px;">
        <h3 style="color: #333; margin-bottom: 10px;">Calculation Traces</h3>
        <div style="font-size: 12px; color: #666; line-height: 1.6;">
          <p><strong>Life Path:</strong> ${results.lifePath.intermediate.digits.join(' + ')} = ${results.lifePath.intermediate.sum} → ${results.lifePath.value}</p>
          <p><strong>Expression:</strong> Name sum = ${results.expression.raw} → ${results.expression.value}</p>
          <p><strong>Soul Urge:</strong> Vowels sum = ${results.soulUrge.raw} → ${results.soulUrge.value}</p>
          <p><strong>Personality:</strong> Consonants sum = ${results.personality.raw} → ${results.personality.value}</p>
        </div>
      </div>
      
      <div style="text-align: center; font-size: 10px; color: #999; margin-top: 30px;">
        <p>Generated by NumenCoach - Numerology guidance based on deterministic calculations</p>
        <p>Visit us at numencoach.app for interactive features</p>
      </div>
    `;

    document.body.appendChild(reportDiv);
    
    // Capture as canvas
    const canvas = await html2canvas(reportDiv, {
      backgroundColor: 'white',
      scale: 2
    });
    
    document.body.removeChild(reportDiv);
    
    // Generate PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 210;
    const pageHeight = 295;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    
    let position = 0;
    
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
    
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }
    
    pdf.save(`NumenCoach_Report_${profile.fullName.replace(/\s+/g, '_')}.pdf`);
  } catch (error) {
    console.error('PDF generation error:', error);
    alert('Error generating PDF. Please try again.');
  }
}